// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS-o7R5MSNdfW_5-HceSdFSnXyvN62RTw',
    appId: '1:146746211247:web:970af97364bb326d1e8d5a',
    messagingSenderId: '146746211247',
    projectId: 'app-sanesoft',
    authDomain: 'app-sanesoft.firebaseapp.com',
    storageBucket: 'app-sanesoft.firebasestorage.app',
    measurementId: 'G-CBM129BKGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJdTqsG6ZwOqghjRCQV08D3-byTrF-bVA',
    appId: '1:146746211247:android:34e10398ab3cd1381e8d5a',
    messagingSenderId: '146746211247',
    projectId: 'app-sanesoft',
    storageBucket: 'app-sanesoft.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS-o7R5MSNdfW_5-HceSdFSnXyvN62RTw',
    appId: '1:146746211247:web:d8bc6155872db50e1e8d5a',
    messagingSenderId: '146746211247',
    projectId: 'app-sanesoft',
    authDomain: 'app-sanesoft.firebaseapp.com',
    storageBucket: 'app-sanesoft.firebasestorage.app',
    measurementId: 'G-CSHSSDBG4B',
  );
}
